# Generated by Django 3.2.16 on 2023-02-12 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityMaster',
            fields=[
                ('ability', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Ability')),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ability_mst',
            },
        ),
        migrations.CreateModel(
            name='FormMaster',
            fields=[
                ('forms', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='forms')),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'forms_mst',
            },
        ),
        migrations.CreateModel(
            name='GenderMaster',
            fields=[
                ('gender', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Gender')),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gender_mst',
            },
        ),
        migrations.CreateModel(
            name='NationalPokedex',
            fields=[
                ('number', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Pokedex number')),
                ('name', models.CharField(max_length=12, unique=True, verbose_name='Pokemon Name')),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'national_pokedex',
            },
        ),
        migrations.CreateModel(
            name='RegionMaster',
            fields=[
                ('region', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Region')),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'region_mst',
            },
        ),
        migrations.CreateModel(
            name='TypeMaster',
            fields=[
                ('type', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Type')),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'type_mst',
            },
        ),
        migrations.CreateModel(
            name='PokemonStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mega_evolution', models.BooleanField(default=False, verbose_name='Mega Evolution')),
                ('primal_reversion', models.BooleanField(default=False, verbose_name='Primal Reversion')),
                ('hp', models.PositiveSmallIntegerField(verbose_name='Hit Point')),
                ('attack', models.PositiveSmallIntegerField(verbose_name='Attack')),
                ('defense', models.PositiveSmallIntegerField(verbose_name='Defense')),
                ('special_attack', models.PositiveSmallIntegerField(verbose_name='Special Attack')),
                ('special_defense', models.PositiveSmallIntegerField(verbose_name='Special Defense')),
                ('speed', models.PositiveSmallIntegerField(verbose_name='Speed')),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forms', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='pokedex.formmaster', verbose_name='Forms')),
                ('gender', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='pokedex.gendermaster', verbose_name='Gender')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokedex.nationalpokedex', verbose_name='National Pokedex Number')),
                ('regional_variant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='pokedex.regionmaster', verbose_name='Regional variant')),
                ('type_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_1', to='pokedex.typemaster', verbose_name='Type 1')),
                ('type_2', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type_2', to='pokedex.typemaster', verbose_name='Type 2')),
            ],
            options={
                'db_table': 'pokemon_status',
            },
        ),
    ]
