# Generated by Django 3.2.16 on 2023-02-07 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NationalPokedex',
            fields=[
                ('number', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Pokedex number')),
                ('name', models.CharField(max_length=12, unique=True, verbose_name='Pokemon Name')),
            ],
            options={
                'db_table': 'national_pokedex',
            },
        ),
        migrations.CreateModel(
            name='PokemonAbility',
            fields=[
                ('ability', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Ability')),
            ],
            options={
                'db_table': 'pokemon_ability',
            },
        ),
        migrations.CreateModel(
            name='PokemonForms',
            fields=[
                ('forms', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='forms')),
            ],
            options={
                'db_table': 'pokemon_forms',
            },
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('type', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Type')),
            ],
            options={
                'db_table': 'pokemon_type',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Region')),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='PokemonStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.PositiveSmallIntegerField(verbose_name='Hit Point')),
                ('attack', models.PositiveSmallIntegerField(verbose_name='Attack')),
                ('defense', models.PositiveSmallIntegerField(verbose_name='Defense')),
                ('special_attack', models.PositiveSmallIntegerField(verbose_name='Special Attack')),
                ('special_defense', models.PositiveSmallIntegerField(verbose_name='Special Defense')),
                ('speed', models.PositiveSmallIntegerField(verbose_name='Speed')),
                ('mega_evolution', models.BooleanField(default=False, verbose_name='Mega Evolution')),
                ('primal_reversion', models.BooleanField(default=False, verbose_name='Primal Reversion')),
                ('ability_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ability_1', to='pokedex.pokemonability', verbose_name='Ability_1')),
                ('ability_2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='ability_2', to='pokedex.pokemonability', verbose_name='Ability_2')),
                ('forms', models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, to='pokedex.pokemonforms', verbose_name='Forms')),
                ('hidden_ability', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='hidden_ability', to='pokedex.pokemonability', verbose_name='Hidden_Ability')),
                ('national_pokedex_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='national_pokedex_number', to='pokedex.nationalpokedex', verbose_name='National Pokedex Number')),
                ('pokemon_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon_name', to='pokedex.nationalpokedex', verbose_name='Pokemon Name')),
                ('regional_variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='pokedex.region', verbose_name='Regional variant')),
                ('type_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_1', to='pokedex.pokemontype', verbose_name='Type_1')),
                ('type_2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='type_2', to='pokedex.pokemontype', verbose_name='Type_2')),
            ],
            options={
                'db_table': 'pokemon_status',
            },
        ),
    ]
