# Generated by Django 3.2.16 on 2023-02-13 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NationalPokedex',
            fields=[
                ('number', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='National Pokedex number')),
                ('name', models.CharField(max_length=12, unique=True, verbose_name='Pokemon Name')),
                ('created_by', models.CharField(max_length=255, verbose_name='Created by')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_by', models.CharField(max_length=255, verbose_name='Updated by')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'national_pokedex',
            },
        ),
        migrations.CreateModel(
            name='TypeMaster',
            fields=[
                ('type', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Type')),
                ('created_by', models.CharField(max_length=255, verbose_name='Created by')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_by', models.CharField(max_length=255, verbose_name='Updated by')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated by')),
            ],
            options={
                'db_table': 'type_mst',
            },
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, verbose_name='Created by')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_by', models.CharField(max_length=255, verbose_name='Updated by')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated by')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokedex.nationalpokedex', verbose_name='National Pokemon Number')),
                ('type_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_1', to='pokedex.typemaster', verbose_name='Type 1')),
                ('type_2', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type_2', to='pokedex.typemaster', verbose_name='Type 2')),
            ],
            options={
                'db_table': 'pokemon_type',
            },
        ),
    ]
